name: multiple_localization_example
description: Demonstrates how to use the multiple_localization plugin.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  multiple_localization_plus:
    path: ../

dev_dependencies:
  # TODO: uncomment when intl_translation are updated
  # intl_translation: ^0.17.7
  flutter_lints: ^2.0.1
